[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"

[compat]
BenchmarkTools = "1"
CUDA = "5"
CairoMakie = "0.15"
IJulia = "1"
KernelAbstractions = "0.9"
ProgressMeter = "1"
